[package]
name = "som-rmqtt-sub"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
# 日期时间处理库
chrono = "0.4.44"
# 颜色库 | 用来实现日志输出自定义颜色的
colored = "3.1.1"

log = "0.4.29"
env_logger = "0.11.10"

serde = { version = "1.0.228", features = ["derive"] }
# JSON5 配置（支持注释）
json5 = "1.3.1"


# MQTT 客户端（轻量）
rumqttc = { version = "0.25.1", default-features = false, features = ["use-native-tls", "use-rustls-no-provider"] }
# 强制在编译时从源码构建 openssl
# 这样 zigbuild 会调用 zig cc 来编译符合 mips 架构的静态 openssl 库
openssl = { version = "0.10.76", features = ["vendored"] }


[profile.release]
# 优先体积优化，而非速度
opt-level = "z"
# 全程序链接优化，移除无用代码
lto = true
# 自动去掉所有调试符号
strip = true
# 最大化优化
codegen-units = 1
# 去掉 panic 处理代码
panic = "abort"